
configs = dict(batch_size=600,
               en_steps=36,
               de_steps=3,
               en_features=30,
               flow_features=15,
               stock_features=4,
               profile_features=8,
               de_features=1,
               en_flow_units=32,
               en_stock_units=16,
               de_cell_units=16,
               profile_cells=16,
               de_out_units=1,
               epoches=400,
               attention_units=32,
               learning_rate=0.01,
               l2e=0.001)
